### ISSUE TITLE
Core dumps instead of "permission denied" on Centos 6.4

### ISSUE THREAD

**Issue by BatmanAoD** [sickill/stderred#31]
"rm" seems to sometimes cause a segfault with stderred in some cases. (Some other programs might do this as well, but "rm" is the only one I came up with a repeatable testcase for. EDIT: see update below.) Adding "rm" to the STDERRED_BLACKLIST doesn't seem to have any effect.

> mkdir /tmp/nodelete
> chmod a-w /tmp/nodelete
> rm /tmp/nodelete     # should fail to delete directory, but shouldn't core dump!
> Segmentation fault (core dumped)
> LD_PRELOAD='' rm /tmp/nodelete
> rm: cannot remove `/tmp/nodelete': Is a directory
> mkdir /tmp/nodelete
> chmod a-w /tmp/nodelete
> export STDERRED_BLACKLIST="^rm"
> rm /tmp/nodelete
> Segmentation fault (core dumped)

Curiously enough, the "Segmentation fault" lines _are_ colored red.

UPDATE: the issue seems to occur almost every time I should get a "permission denied" error. Here's an example using `ls`.

> mkdir /tmp/personal_tmp/privdir
> touch /tmp/personal_tmp/privdir/newfile
> chmod a-x /tmp/personal_tmp/privdir
> ls /tmp/personal_tmp/privdir
> Segmentation fault (core dumped)
> export LD_PRELOAD=
> ls /tmp/personal_tmp/privdir
> ls: cannot access /tmp/personal_tmp/privdir/newfile: Permission denied
> newfile

**Comment by cehoffman** [comment]
I think this may have been fixed in dfe65c8034c027f910ca473ca778dd4c27211b0c.

@BatmanAoD could you verify if this works for you?

**Comment by cmarqu** [comment]
This still happens with RHEL 6.9 unfortunately (and also SuSE 11). Test 13 and 14 also fail (both with ``***Exception: SegFault``).
